MCU        = RP2040
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE  = yes
EXTRAKEY_ENABLE  = yes
CONSOLE_ENABLE   = no
COMMAND_ENABLE   = no
NKRO_ENABLE      = yes

JOYSTICK_ENABLE  = yes
JOYSTICK_DRIVER  = analog

VIA_ENABLE       = no
LTO_ENABLE       = yes
